### ISSUE TITLE
Post.parent() gives wrong query.

### ISSUE THREAD

**Issue by VandorpeDavid** [asiniy/ecto_materialized_path#4]
```
post |> Post.parent() |> Repo.one()
```
results in

> ** (Ecto.Query.CastError) deps/ecto_materialized_path/lib/ecto_materialized_path.ex:73: value `4` in `where` cannot be cast to type {:in, :id} in query:
> 
> from a in Post
>   where: a.id in ^4,
>   limit: 1,
>   select: a
> 
>     (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
>     (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
>     (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
>     (ecto) lib/ecto/repo/queryable.ex:124: Ecto.Repo.Queryable.execute/5
>     (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
>     (ecto) lib/ecto/repo/queryable.ex:70: Ecto.Repo.Queryable.one/4
>     (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
>     (iex) lib/iex/evaluator.ex:250: IEx.Evaluator.handle_eval/5
>     (iex) lib/iex/evaluator.ex:230: IEx.Evaluator.do_eval/3
>     (iex) lib/iex/evaluator.ex:208: IEx.Evaluator.eval/3

Running `post |> Post.parent()` returns

> #Ecto.Query<from a in Post, where: a.id in ^4, limit: 1>

The use of the `in` operator seems weird to me, but it has been there for over a year, and noone has complained yet. This makes me wonder if I am doing something wrong.

**Comment by casual-smart** [comment]
Same here

Test case to reproduce:

```elixir
    setup do
      root = Repo.insert!(%Comment{text: "hey"})

      child =
        %Comment{text: "hello"}
        |> Comment.make_child_of(root)
        |> Repo.insert!()

      {:ok, root: root, child: child}
    end

    test "parent/1", %{root: %Comment{id: root_id}, child: child} do
      assert %Comment{id: ^root_id} =
               child
               |> Comment.parent()
               |> Repo.one!()
    end
```
fails with
```
     test/demo_test.exs:53
     ** (Ecto.Query.CastError) deps/ecto_materialized_path/lib/ecto_materialized_path.ex:73: value `11` in `where` cannot be cast to type {:in, :id} in query:

     from c0 in Demo.Comment,
       where: c0.id in ^11,
       limit: 1,
       select: c0

     code: |> Repo.one!()
     stacktrace:
       (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1431: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/repo/queryable.ex:138: Ecto.Repo.Queryable.execute/4
       (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
       (ecto) lib/ecto/repo/queryable.ex:75: Ecto.Repo.Queryable.one!/3
       test/demo_test.exs:57: (test)
```

**Comment by casual-smart** [comment]
Current workaround that I use

```elixir
    test "parent/1 workaround", %{root: %Comment{id: root_id}, child: child} do
      assert %Comment{id: ^root_id} =
               Comment
               |> where(id: ^Comment.parent_id(child))
               |> Repo.one!()
    end
```
